### ISSUE TITLE
trac ticket 9363 can be closed

### ISSUE THREAD

**Issue by Kojoley** [boostorg/phoenix#75]
The [trac ticket 9363](https://svn.boost.org/trac10/ticket/9363) problem seems to be fixed in Boost 1.63 (possibly in 0c401e7c121a67e838a58c7253663440acd59ef7) and can be closed. 

*I opened an issue here because trac comments are closed for me.*

cc @Lastique

**Comment by Lastique** [comment]
The test case from that ticket compiles with gcc 8.2 and Boost 1.68 and the current develop. Thanks!

**Comment by Flast** [comment]
good catch!
